version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # Download and cache dependencies
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 



workflows:
  build_and_deploy:
    jobs:
      - lint
      - aws-ecr/build-and-push-image:
          name: build_and_push
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION 
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 10m
          path: ~/app/
          repo: capstone
          skip-when-tags-exist: false
          tag: ${CIRCLE_SHA1}

